---
apiVersion: v1
kind: Service
metadata:
  name: clamav-rest-service-metrics
  namespace: clamav-rest
  labels:
    app: clamav-rest-service
spec:
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 443
    targetPort: 9443
  selector:
    app: clamav-rest-service
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: clamav-rest-service
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
    app: clamav-rest-service
spec:
  endpoints:
  - interval: 60s
    path: /metrics
    port: metrics
    scheme: https
    tlsConfig:
      insecureSkipVerify: true
  namespaceSelector:
    matchNames: 
    - clamav-rest-service
  selector:
    matchLabels:
      app: clamav-rest-service